# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asp3d_layout.ui'
#
# Created: Fri Mar 10 10:39:39 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1864, 1557)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(250000, 350000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../.designer/asp3d_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.seisarray_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seisarray_active.sizePolicy().hasHeightForWidth())
        self.seisarray_active.setSizePolicy(sizePolicy)
        self.seisarray_active.setMaximumSize(QtCore.QSize(400, 20))
        self.seisarray_active.setMidLineWidth(0)
        self.seisarray_active.setText("")
        self.seisarray_active.setObjectName("seisarray_active")
        self.horizontalLayout_2.addWidget(self.seisarray_active)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.seisarray_on_survey_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seisarray_on_survey_active.sizePolicy().hasHeightForWidth())
        self.seisarray_on_survey_active.setSizePolicy(sizePolicy)
        self.seisarray_on_survey_active.setMaximumSize(QtCore.QSize(400, 20))
        self.seisarray_on_survey_active.setMidLineWidth(0)
        self.seisarray_on_survey_active.setText("")
        self.seisarray_on_survey_active.setObjectName("seisarray_on_survey_active")
        self.horizontalLayout_2.addWidget(self.seisarray_on_survey_active)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(400, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.textBox_seisarray = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_seisarray.sizePolicy().hasHeightForWidth())
        self.textBox_seisarray.setSizePolicy(sizePolicy)
        self.textBox_seisarray.setMinimumSize(QtCore.QSize(200, 0))
        self.textBox_seisarray.setMaximumSize(QtCore.QSize(400, 150))
        self.textBox_seisarray.setReadOnly(True)
        self.textBox_seisarray.setObjectName("textBox_seisarray")
        self.verticalLayout_2.addWidget(self.textBox_seisarray)
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 5))
        self.line.setMaximumSize(QtCore.QSize(400, 16777215))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_3.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.survey_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.survey_active.sizePolicy().hasHeightForWidth())
        self.survey_active.setSizePolicy(sizePolicy)
        self.survey_active.setMaximumSize(QtCore.QSize(400, 20))
        self.survey_active.setMidLineWidth(0)
        self.survey_active.setText("")
        self.survey_active.setObjectName("survey_active")
        self.horizontalLayout.addWidget(self.survey_active)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.picked_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picked_active.sizePolicy().hasHeightForWidth())
        self.picked_active.setSizePolicy(sizePolicy)
        self.picked_active.setMaximumSize(QtCore.QSize(400, 20))
        self.picked_active.setMidLineWidth(0)
        self.picked_active.setText("")
        self.picked_active.setObjectName("picked_active")
        self.horizontalLayout.addWidget(self.picked_active)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(400, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBox_survey = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_survey.sizePolicy().hasHeightForWidth())
        self.textBox_survey.setSizePolicy(sizePolicy)
        self.textBox_survey.setMinimumSize(QtCore.QSize(200, 0))
        self.textBox_survey.setMaximumSize(QtCore.QSize(400, 150))
        self.textBox_survey.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBox_survey.setObjectName("textBox_survey")
        self.verticalLayout_2.addWidget(self.textBox_survey)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(200, 0))
        self.label_7.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.textBox_terminal = QtGui.QTextEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_terminal.sizePolicy().hasHeightForWidth())
        self.textBox_terminal.setSizePolicy(sizePolicy)
        self.textBox_terminal.setMinimumSize(QtCore.QSize(200, 0))
        self.textBox_terminal.setMaximumSize(QtCore.QSize(400, 16777215))
        self.textBox_terminal.setReadOnly(True)
        self.textBox_terminal.setObjectName("textBox_terminal")
        self.verticalLayout_8.addWidget(self.textBox_terminal)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textBox_terminal_err = QtGui.QTextEdit(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_terminal_err.sizePolicy().hasHeightForWidth())
        self.textBox_terminal_err.setSizePolicy(sizePolicy)
        self.textBox_terminal_err.setMinimumSize(QtCore.QSize(200, 0))
        self.textBox_terminal_err.setMaximumSize(QtCore.QSize(400, 16777215))
        self.textBox_terminal_err.setReadOnly(True)
        self.textBox_terminal_err.setObjectName("textBox_terminal_err")
        self.verticalLayout_10.addWidget(self.textBox_terminal_err)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_right = QtGui.QVBoxLayout()
        self.verticalLayout_right.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.horizontalLayout_tr = QtGui.QHBoxLayout()
        self.horizontalLayout_tr.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_tr.setObjectName("horizontalLayout_tr")
        self.horizontalLayout_sa = QtGui.QHBoxLayout()
        self.horizontalLayout_sa.setObjectName("horizontalLayout_sa")
        self.verticalLayout_sa_tbar = QtGui.QVBoxLayout()
        self.verticalLayout_sa_tbar.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_sa_tbar.setObjectName("verticalLayout_sa_tbar")
        self.horizontalLayout_sa.addLayout(self.verticalLayout_sa_tbar)
        self.verticalLayout_sa_plot = QtGui.QVBoxLayout()
        self.verticalLayout_sa_plot.setObjectName("verticalLayout_sa_plot")
        self.horizontalLayout_sa.addLayout(self.verticalLayout_sa_plot)
        self.horizontalLayout_sa.setStretch(0, 1)
        self.horizontalLayout_tr.addLayout(self.horizontalLayout_sa)
        self.horizontalLayout_surf = QtGui.QHBoxLayout()
        self.horizontalLayout_surf.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_surf.setObjectName("horizontalLayout_surf")
        self.horizontalLayout_tr.addLayout(self.horizontalLayout_surf)
        self.horizontalLayout_tr.setStretch(0, 1)
        self.horizontalLayout_tr.setStretch(1, 1)
        self.verticalLayout_right.addLayout(self.horizontalLayout_tr)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_right.addWidget(self.line_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.comboBox_stats = QtGui.QComboBox(self.centralwidget)
        self.comboBox_stats.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_stats.sizePolicy().hasHeightForWidth())
        self.comboBox_stats.setSizePolicy(sizePolicy)
        self.comboBox_stats.setMinimumSize(QtCore.QSize(450, 20))
        self.comboBox_stats.setObjectName("comboBox_stats")
        self.verticalLayout_6.addWidget(self.comboBox_stats)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.shot_left = QtGui.QPushButton(self.centralwidget)
        self.shot_left.setMinimumSize(QtCore.QSize(0, 20))
        self.shot_left.setMaximumSize(QtCore.QSize(30, 16777215))
        self.shot_left.setObjectName("shot_left")
        self.horizontalLayout_4.addWidget(self.shot_left)
        self.comboBox_shots = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_shots.sizePolicy().hasHeightForWidth())
        self.comboBox_shots.setSizePolicy(sizePolicy)
        self.comboBox_shots.setMinimumSize(QtCore.QSize(150, 20))
        self.comboBox_shots.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_shots.setObjectName("comboBox_shots")
        self.horizontalLayout_4.addWidget(self.comboBox_shots)
        self.shot_right = QtGui.QPushButton(self.centralwidget)
        self.shot_right.setMinimumSize(QtCore.QSize(0, 20))
        self.shot_right.setMaximumSize(QtCore.QSize(30, 16777215))
        self.shot_right.setObjectName("shot_right")
        self.horizontalLayout_4.addWidget(self.shot_right)
        self.plot_shot = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_shot.sizePolicy().hasHeightForWidth())
        self.plot_shot.setSizePolicy(sizePolicy)
        self.plot_shot.setMinimumSize(QtCore.QSize(0, 20))
        self.plot_shot.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_shot.setObjectName("plot_shot")
        self.horizontalLayout_4.addWidget(self.plot_shot)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout_right.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_br = QtGui.QHBoxLayout()
        self.horizontalLayout_br.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_br.setObjectName("horizontalLayout_br")
        self.horizontalLayout_br1 = QtGui.QHBoxLayout()
        self.horizontalLayout_br1.setObjectName("horizontalLayout_br1")
        self.verticalLayout_rec_tbar = QtGui.QVBoxLayout()
        self.verticalLayout_rec_tbar.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_rec_tbar.setObjectName("verticalLayout_rec_tbar")
        self.horizontalLayout_br1.addLayout(self.verticalLayout_rec_tbar)
        self.verticalLayout_rec_plot = QtGui.QVBoxLayout()
        self.verticalLayout_rec_plot.setObjectName("verticalLayout_rec_plot")
        self.horizontalLayout_br1.addLayout(self.verticalLayout_rec_plot)
        self.horizontalLayout_br1.setStretch(0, 1)
        self.horizontalLayout_br1.setStretch(1, 20)
        self.horizontalLayout_br.addLayout(self.horizontalLayout_br1)
        self.horizontalLayout_br2 = QtGui.QHBoxLayout()
        self.horizontalLayout_br2.setObjectName("horizontalLayout_br2")
        self.verticalLayout_shot_tbar = QtGui.QVBoxLayout()
        self.verticalLayout_shot_tbar.setObjectName("verticalLayout_shot_tbar")
        self.horizontalLayout_br2.addLayout(self.verticalLayout_shot_tbar)
        self.verticalLayout_shot_plot = QtGui.QVBoxLayout()
        self.verticalLayout_shot_plot.setObjectName("verticalLayout_shot_plot")
        self.horizontalLayout_br2.addLayout(self.verticalLayout_shot_plot)
        self.horizontalLayout_br2.setStretch(0, 1)
        self.horizontalLayout_br2.setStretch(1, 20)
        self.horizontalLayout_br.addLayout(self.horizontalLayout_br2)
        self.horizontalLayout_br.setStretch(0, 1)
        self.horizontalLayout_br.setStretch(1, 1)
        self.verticalLayout_right.addLayout(self.horizontalLayout_br)
        self.verticalLayout_right.setStretch(0, 10)
        self.verticalLayout_right.setStretch(3, 10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_right)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1864, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSeismic_Array = QtGui.QMenu(self.menubar)
        self.menuSeismic_Array.setObjectName("menuSeismic_Array")
        self.menuPicking = QtGui.QMenu(self.menubar)
        self.menuPicking.setObjectName("menuPicking")
        self.menuExport_Picks = QtGui.QMenu(self.menuPicking)
        self.menuExport_Picks.setObjectName("menuExport_Picks")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuManual_Revision = QtGui.QMenu(self.menubar)
        self.menuManual_Revision.setObjectName("menuManual_Revision")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Seismic_Array = QtGui.QAction(MainWindow)
        self.actionLoad_Seismic_Array.setCheckable(False)
        self.actionLoad_Seismic_Array.setObjectName("actionLoad_Seismic_Array")
        self.actionSave_Seismic_Array = QtGui.QAction(MainWindow)
        self.actionSave_Seismic_Array.setObjectName("actionSave_Seismic_Array")
        self.actionLoad_Survey = QtGui.QAction(MainWindow)
        self.actionLoad_Survey.setObjectName("actionLoad_Survey")
        self.actionSave_Survey = QtGui.QAction(MainWindow)
        self.actionSave_Survey.setObjectName("actionSave_Survey")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGenerate_new_Seismic_Array = QtGui.QAction(MainWindow)
        self.actionGenerate_new_Seismic_Array.setObjectName("actionGenerate_new_Seismic_Array")
        self.actionInterpolate_Receivers = QtGui.QAction(MainWindow)
        self.actionInterpolate_Receivers.setObjectName("actionInterpolate_Receivers")
        self.actionConnect_to_Survey = QtGui.QAction(MainWindow)
        self.actionConnect_to_Survey.setObjectName("actionConnect_to_Survey")
        self.actionGenerate_new_Survey = QtGui.QAction(MainWindow)
        self.actionGenerate_new_Survey.setObjectName("actionGenerate_new_Survey")
        self.actionAutomatic_Picking = QtGui.QAction(MainWindow)
        self.actionAutomatic_Picking.setObjectName("actionAutomatic_Picking")
        self.actionPostprocessing = QtGui.QAction(MainWindow)
        self.actionPostprocessing.setObjectName("actionPostprocessing")
        self.actionStart_FMTOMO_Simulation = QtGui.QAction(MainWindow)
        self.actionStart_FMTOMO_Simulation.setObjectName("actionStart_FMTOMO_Simulation")
        self.actionVTK_Visualization = QtGui.QAction(MainWindow)
        self.actionVTK_Visualization.setObjectName("actionVTK_Visualization")
        self.actionSeismic_Array = QtGui.QAction(MainWindow)
        self.actionSeismic_Array.setEnabled(False)
        self.actionSeismic_Array.setObjectName("actionSeismic_Array")
        self.actionFullscreen = QtGui.QAction(MainWindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionMerge_Shots = QtGui.QAction(MainWindow)
        self.actionMerge_Shots.setObjectName("actionMerge_Shots")
        self.actionASCII_File = QtGui.QAction(MainWindow)
        self.actionASCII_File.setObjectName("actionASCII_File")
        self.actionExport_Receiver_Locations = QtGui.QAction(MainWindow)
        self.actionExport_Receiver_Locations.setObjectName("actionExport_Receiver_Locations")
        self.actionPlotAllShots = QtGui.QAction(MainWindow)
        self.actionPlotAllShots.setObjectName("actionPlotAllShots")
        self.menuFile.addAction(self.actionGenerate_new_Survey)
        self.menuFile.addAction(self.actionLoad_Survey)
        self.menuFile.addAction(self.actionSave_Survey)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionGenerate_new_Seismic_Array)
        self.menuFile.addAction(self.actionLoad_Seismic_Array)
        self.menuFile.addAction(self.actionSave_Seismic_Array)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSeismic_Array.addAction(self.actionInterpolate_Receivers)
        self.menuSeismic_Array.addAction(self.actionExport_Receiver_Locations)
        self.menuExport_Picks.addAction(self.actionASCII_File)
        self.menuPicking.addAction(self.actionAutomatic_Picking)
        self.menuPicking.addAction(self.menuExport_Picks.menuAction())
        self.menuSimulation.addAction(self.actionStart_FMTOMO_Simulation)
        self.menuTools.addAction(self.actionVTK_Visualization)
        self.menuTools.addAction(self.actionMerge_Shots)
        self.menuView.addAction(self.actionFullscreen)
        self.menuManual_Revision.addAction(self.actionPostprocessing)
        self.menuManual_Revision.addAction(self.actionPlotAllShots)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSeismic_Array.menuAction())
        self.menubar.addAction(self.menuPicking.menuAction())
        self.menubar.addAction(self.menuManual_Revision.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ActiveSeismoPick 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Current Seismic Array object", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "connected to Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Current Survey object", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "active", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "picked", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Terminal output:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Error/Warnings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Plot Receiver and Shots of the Array colored by:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Plot a single Shot (and repick traces):", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_left.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_right.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_shot.setText(QtGui.QApplication.translate("MainWindow", "Plot Single", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSeismic_Array.setTitle(QtGui.QApplication.translate("MainWindow", "Array Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPicking.setTitle(QtGui.QApplication.translate("MainWindow", "Picking", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport_Picks.setTitle(QtGui.QApplication.translate("MainWindow", "Export Picks", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Inversion", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuManual_Revision.setTitle(QtGui.QApplication.translate("MainWindow", "Manual Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Seismic_Array.setText(QtGui.QApplication.translate("MainWindow", "Load Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Seismic_Array.setText(QtGui.QApplication.translate("MainWindow", "Save Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Survey.setText(QtGui.QApplication.translate("MainWindow", "Load Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Survey.setText(QtGui.QApplication.translate("MainWindow", "Save Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_new_Seismic_Array.setText(QtGui.QApplication.translate("MainWindow", "New Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_new_Seismic_Array.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>A SeisArray object stores geometry information of the Survey (mainly sources and receiver locations).</p><p><br/></p><p>It may load those files in a specific structure (see tooltips in the next dialog) to interpolate for unknown geophone locations along a geophone line.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInterpolate_Receivers.setText(QtGui.QApplication.translate("MainWindow", "Interpolate Receivers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_Survey.setText(QtGui.QApplication.translate("MainWindow", "Connect Seismic Array to Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_new_Survey.setText(QtGui.QApplication.translate("MainWindow", "New Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_new_Survey.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Generate a new Survey object.</p><p><br/></p><p>A Survey object automatically uses given geometry information of the Survey to generate and save a SeisArray object as an attribute, which stores geometry information of the Survey (mainly sources and receiver locations).</p><p><br/></p><p>It also opens and stores waveform data of the Survey, as they are found for the corresponding source ID\'s (source locations input file). </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutomatic_Picking.setText(QtGui.QApplication.translate("MainWindow", "Automatic Picking/SNR", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPostprocessing.setText(QtGui.QApplication.translate("MainWindow", "Scatter Plot of all Picks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_FMTOMO_Simulation.setText(QtGui.QApplication.translate("MainWindow", "Start FMTOMO Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVTK_Visualization.setText(QtGui.QApplication.translate("MainWindow", "VTK Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSeismic_Array.setText(QtGui.QApplication.translate("MainWindow", "Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("MainWindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMerge_Shots.setText(QtGui.QApplication.translate("MainWindow", "Merge Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASCII_File.setText(QtGui.QApplication.translate("MainWindow", "ASCII File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Receiver_Locations.setText(QtGui.QApplication.translate("MainWindow", "Export Receiver Locations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlotAllShots.setText(QtGui.QApplication.translate("MainWindow", "Plot of all Shots", None, QtGui.QApplication.UnicodeUTF8))

