# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export2ascii_layout.ui'
#
# Created: Fri Mar 10 10:39:40 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_export2ascii(object):
    def setupUi(self, export2ascii):
        export2ascii.setObjectName("export2ascii")
        export2ascii.resize(355, 216)
        self.verticalLayout_3 = QtGui.QVBoxLayout(export2ascii)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtGui.QLabel(export2ascii)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(export2ascii)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_outfolder = QtGui.QLineEdit(export2ascii)
        self.lineEdit_outfolder.setObjectName("lineEdit_outfolder")
        self.horizontalLayout_2.addWidget(self.lineEdit_outfolder)
        self.pushButton_outfolder = QtGui.QPushButton(export2ascii)
        self.pushButton_outfolder.setObjectName("pushButton_outfolder")
        self.horizontalLayout_2.addWidget(self.pushButton_outfolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_add_invalid = QtGui.QCheckBox(export2ascii)
        self.checkBox_add_invalid.setChecked(True)
        self.checkBox_add_invalid.setObjectName("checkBox_add_invalid")
        self.horizontalLayout.addWidget(self.checkBox_add_invalid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(export2ascii)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_invalid_value = QtGui.QLineEdit(export2ascii)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_invalid_value.sizePolicy().hasHeightForWidth())
        self.lineEdit_invalid_value.setSizePolicy(sizePolicy)
        self.lineEdit_invalid_value.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_invalid_value.setObjectName("lineEdit_invalid_value")
        self.horizontalLayout_3.addWidget(self.lineEdit_invalid_value)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_add_pickerror = QtGui.QCheckBox(export2ascii)
        self.checkBox_add_pickerror.setObjectName("checkBox_add_pickerror")
        self.horizontalLayout_4.addWidget(self.checkBox_add_pickerror)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(export2ascii)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(export2ascii)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), export2ascii.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), export2ascii.reject)
        QtCore.QMetaObject.connectSlotsByName(export2ascii)

    def retranslateUi(self, export2ascii):
        export2ascii.setWindowTitle(QtGui.QApplication.translate("export2ascii", "Export to ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("export2ascii", "<html><head/><body><p>Generate simple ASCII output files containing all picks for each shot with each column containing: (1) traceID    (2) t_pick    (3) pickerror (optional)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("export2ascii", "Generate ASCII files containing picks [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("export2ascii", "Browse for output folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_outfolder.setText(QtGui.QApplication.translate("export2ascii", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_add_invalid.setText(QtGui.QApplication.translate("export2ascii", "Add value for inexistent/deleted picks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("export2ascii", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_invalid_value.setText(QtGui.QApplication.translate("export2ascii", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_add_pickerror.setText(QtGui.QApplication.translate("export2ascii", "Add pick error", None, QtGui.QApplication.UnicodeUTF8))

