# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'merge_shots_layout.ui'
#
# Created: Fri Mar 10 10:39:40 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_merge_shots(object):
    def setupUi(self, merge_shots):
        merge_shots.setObjectName("merge_shots")
        merge_shots.resize(800, 800)
        merge_shots.setMinimumSize(QtCore.QSize(300, 150))
        self.verticalLayout_3 = QtGui.QVBoxLayout(merge_shots)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_general = QtGui.QCheckBox(merge_shots)
        self.checkBox_general.setEnabled(True)
        self.checkBox_general.setObjectName("checkBox_general")
        self.verticalLayout_2.addWidget(self.checkBox_general)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_location = QtGui.QLabel(merge_shots)
        self.label_location.setEnabled(False)
        self.label_location.setObjectName("label_location")
        self.gridLayout.addWidget(self.label_location, 1, 0, 1, 1)
        self.lineEdit_location = QtGui.QLineEdit(merge_shots)
        self.lineEdit_location.setEnabled(False)
        self.lineEdit_location.setObjectName("lineEdit_location")
        self.gridLayout.addWidget(self.lineEdit_location, 1, 1, 1, 1)
        self.label_station = QtGui.QLabel(merge_shots)
        self.label_station.setEnabled(False)
        self.label_station.setObjectName("label_station")
        self.gridLayout.addWidget(self.label_station, 0, 2, 1, 1)
        self.label_network = QtGui.QLabel(merge_shots)
        self.label_network.setEnabled(False)
        self.label_network.setObjectName("label_network")
        self.gridLayout.addWidget(self.label_network, 0, 0, 1, 1)
        self.lineEdit_network = QtGui.QLineEdit(merge_shots)
        self.lineEdit_network.setEnabled(False)
        self.lineEdit_network.setObjectName("lineEdit_network")
        self.gridLayout.addWidget(self.lineEdit_network, 0, 1, 1, 1)
        self.lineEdit_station = QtGui.QLineEdit(merge_shots)
        self.lineEdit_station.setEnabled(False)
        self.lineEdit_station.setObjectName("lineEdit_station")
        self.gridLayout.addWidget(self.lineEdit_station, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(merge_shots)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_input = QtGui.QLineEdit(merge_shots)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout_2.addWidget(self.lineEdit_input)
        self.pushButton_browse = QtGui.QPushButton(merge_shots)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout_2.addWidget(self.pushButton_browse)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(merge_shots)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox_nshots = QtGui.QSpinBox(merge_shots)
        self.spinBox_nshots.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nshots.setMinimum(1)
        self.spinBox_nshots.setMaximum(10000)
        self.spinBox_nshots.setObjectName("spinBox_nshots")
        self.horizontalLayout.addWidget(self.spinBox_nshots)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(merge_shots)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_part = QtGui.QSpinBox(merge_shots)
        self.spinBox_part.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_part.setMinimum(1)
        self.spinBox_part.setMaximum(1)
        self.spinBox_part.setObjectName("spinBox_part")
        self.horizontalLayout.addWidget(self.spinBox_part)
        self.pushButton_add = QtGui.QPushButton(merge_shots)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tableView = QtGui.QTableView(merge_shots)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setShowGrid(True)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_merge = QtGui.QPushButton(merge_shots)
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.horizontalLayout_3.addWidget(self.pushButton_merge)
        self.pushButton_save = QtGui.QPushButton(merge_shots)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_3.addWidget(self.pushButton_save)
        self.buttonBox = QtGui.QDialogButtonBox(merge_shots)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(merge_shots)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), merge_shots.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), merge_shots.reject)
        QtCore.QMetaObject.connectSlotsByName(merge_shots)

    def retranslateUi(self, merge_shots):
        merge_shots.setWindowTitle(QtGui.QApplication.translate("merge_shots", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_general.setText(QtGui.QApplication.translate("merge_shots", "General Settings (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_location.setText(QtGui.QApplication.translate("merge_shots", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_station.setText(QtGui.QApplication.translate("merge_shots", "Station", None, QtGui.QApplication.UnicodeUTF8))
        self.label_network.setText(QtGui.QApplication.translate("merge_shots", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browse.setText(QtGui.QApplication.translate("merge_shots", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("merge_shots", "Maximum number of shots for each part", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("merge_shots", "Part", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add.setText(QtGui.QApplication.translate("merge_shots", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_merge.setText(QtGui.QApplication.translate("merge_shots", "Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setText(QtGui.QApplication.translate("merge_shots", "Save...", None, QtGui.QApplication.UnicodeUTF8))

