# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picking_parameters_layout.ui'
#
# Created: Fri Mar 10 10:39:40 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_picking_parameters(object):
    def setupUi(self, picking_parameters):
        picking_parameters.setObjectName("picking_parameters")
        picking_parameters.resize(1600, 900)
        picking_parameters.setMinimumSize(QtCore.QSize(640, 480))
        self.verticalLayout_3 = QtGui.QVBoxLayout(picking_parameters)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.ncores = QtGui.QSpinBox(picking_parameters)
        self.ncores.setMinimumSize(QtCore.QSize(0, 20))
        self.ncores.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ncores.setMinimum(1)
        self.ncores.setMaximum(10000)
        self.ncores.setObjectName("ncores")
        self.gridLayout.addWidget(self.ncores, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_vmax = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_vmax.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_vmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_vmax.setObjectName("lineEdit_vmax")
        self.gridLayout.addWidget(self.lineEdit_vmax, 1, 5, 1, 1)
        self.label_20 = QtGui.QLabel(picking_parameters)
        self.label_20.setMinimumSize(QtCore.QSize(0, 20))
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 6, 1, 1)
        self.label_3 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.label_19 = QtGui.QLabel(picking_parameters)
        self.label_19.setMinimumSize(QtCore.QSize(0, 20))
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 2, 1, 1)
        self.label = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_vmin = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_vmin.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_vmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_vmin.setObjectName("lineEdit_vmin")
        self.gridLayout.addWidget(self.lineEdit_vmin, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(picking_parameters)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_21 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 4, 1, 1)
        self.doubleSpinBox_tmovwind = QtGui.QDoubleSpinBox(picking_parameters)
        self.doubleSpinBox_tmovwind.setMinimumSize(QtCore.QSize(0, 20))
        self.doubleSpinBox_tmovwind.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_tmovwind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_tmovwind.setDecimals(2)
        self.doubleSpinBox_tmovwind.setMinimum(0.0)
        self.doubleSpinBox_tmovwind.setMaximum(10000.0)
        self.doubleSpinBox_tmovwind.setSingleStep(0.01)
        self.doubleSpinBox_tmovwind.setProperty("value", 0.3)
        self.doubleSpinBox_tmovwind.setObjectName("doubleSpinBox_tmovwind")
        self.gridLayout_3.addWidget(self.doubleSpinBox_tmovwind, 1, 3, 1, 1)
        self.doubleSpinBox_cut_right = QtGui.QDoubleSpinBox(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_cut_right.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_cut_right.setSizePolicy(sizePolicy)
        self.doubleSpinBox_cut_right.setMinimumSize(QtCore.QSize(100, 20))
        self.doubleSpinBox_cut_right.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_cut_right.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_cut_right.setDecimals(2)
        self.doubleSpinBox_cut_right.setMinimum(0.0)
        self.doubleSpinBox_cut_right.setMaximum(10000.0)
        self.doubleSpinBox_cut_right.setSingleStep(0.01)
        self.doubleSpinBox_cut_right.setProperty("value", 0.2)
        self.doubleSpinBox_cut_right.setObjectName("doubleSpinBox_cut_right")
        self.gridLayout_3.addWidget(self.doubleSpinBox_cut_right, 0, 5, 1, 1)
        self.label_29 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(0, 20))
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(picking_parameters)
        self.label_16.setMinimumSize(QtCore.QSize(0, 20))
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_23 = QtGui.QLabel(picking_parameters)
        self.label_23.setMinimumSize(QtCore.QSize(0, 20))
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 20))
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 6, 1, 1)
        self.doubleSpinBox_cut_left = QtGui.QDoubleSpinBox(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_cut_left.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_cut_left.setSizePolicy(sizePolicy)
        self.doubleSpinBox_cut_left.setMinimumSize(QtCore.QSize(100, 20))
        self.doubleSpinBox_cut_left.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_cut_left.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_cut_left.setDecimals(2)
        self.doubleSpinBox_cut_left.setMinimum(0.0)
        self.doubleSpinBox_cut_left.setMaximum(10000.0)
        self.doubleSpinBox_cut_left.setSingleStep(0.01)
        self.doubleSpinBox_cut_left.setProperty("value", 0.0)
        self.doubleSpinBox_cut_left.setObjectName("doubleSpinBox_cut_left")
        self.gridLayout_3.addWidget(self.doubleSpinBox_cut_left, 0, 3, 1, 1)
        self.label_24 = QtGui.QLabel(picking_parameters)
        self.label_24.setMinimumSize(QtCore.QSize(0, 20))
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.line_3 = QtGui.QFrame(picking_parameters)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.slider_folm = QtGui.QSlider(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_folm.sizePolicy().hasHeightForWidth())
        self.slider_folm.setSizePolicy(sizePolicy)
        self.slider_folm.setMinimumSize(QtCore.QSize(0, 20))
        self.slider_folm.setMinimum(1)
        self.slider_folm.setMaximum(100)
        self.slider_folm.setProperty("value", 60)
        self.slider_folm.setOrientation(QtCore.Qt.Horizontal)
        self.slider_folm.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_folm.setTickInterval(10)
        self.slider_folm.setObjectName("slider_folm")
        self.horizontalLayout_11.addWidget(self.slider_folm)
        self.label_folm = QtGui.QLabel(picking_parameters)
        self.label_folm.setMinimumSize(QtCore.QSize(0, 20))
        self.label_folm.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_folm.setObjectName("label_folm")
        self.horizontalLayout_11.addWidget(self.label_folm)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_11)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_aicright = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_aicright.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_aicright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_aicright.setObjectName("lineEdit_aicright")
        self.gridLayout_5.addWidget(self.lineEdit_aicright, 0, 2, 1, 1)
        self.lineEdit_aicleft = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_aicleft.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_aicleft.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_aicleft.setObjectName("lineEdit_aicleft")
        self.gridLayout_5.addWidget(self.lineEdit_aicleft, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 40))
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 4, 1, 1)
        self.checkBox_AIC = QtGui.QCheckBox(picking_parameters)
        self.checkBox_AIC.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_AIC.setText("")
        self.checkBox_AIC.setChecked(True)
        self.checkBox_AIC.setObjectName("checkBox_AIC")
        self.gridLayout_6.addWidget(self.checkBox_AIC, 0, 1, 1, 1)
        self.checkBox_threading = QtGui.QCheckBox(picking_parameters)
        self.checkBox_threading.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBox_threading.setText("")
        self.checkBox_threading.setChecked(True)
        self.checkBox_threading.setObjectName("checkBox_threading")
        self.gridLayout_6.addWidget(self.checkBox_threading, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(picking_parameters)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.line_5 = QtGui.QFrame(picking_parameters)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_18 = QtGui.QLabel(picking_parameters)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_26 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 3, 1, 1)
        self.label_25 = QtGui.QLabel(picking_parameters)
        self.label_25.setMinimumSize(QtCore.QSize(0, 20))
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(picking_parameters)
        self.label_28.setMinimumSize(QtCore.QSize(0, 20))
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 6, 1, 1)
        self.doubleSpinBox_tsignal = QtGui.QDoubleSpinBox(picking_parameters)
        self.doubleSpinBox_tsignal.setMinimumSize(QtCore.QSize(100, 20))
        self.doubleSpinBox_tsignal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_tsignal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_tsignal.setDecimals(4)
        self.doubleSpinBox_tsignal.setMinimum(0.0)
        self.doubleSpinBox_tsignal.setMaximum(10000.0)
        self.doubleSpinBox_tsignal.setSingleStep(0.0001)
        self.doubleSpinBox_tsignal.setProperty("value", 0.03)
        self.doubleSpinBox_tsignal.setObjectName("doubleSpinBox_tsignal")
        self.gridLayout_8.addWidget(self.doubleSpinBox_tsignal, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 20))
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 0, 4, 1, 1)
        self.doubleSpinBox_tgap = QtGui.QDoubleSpinBox(picking_parameters)
        self.doubleSpinBox_tgap.setMinimumSize(QtCore.QSize(100, 20))
        self.doubleSpinBox_tgap.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_tgap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_tgap.setDecimals(6)
        self.doubleSpinBox_tgap.setMinimum(0.0)
        self.doubleSpinBox_tgap.setMaximum(10000.0)
        self.doubleSpinBox_tgap.setSingleStep(1e-06)
        self.doubleSpinBox_tgap.setProperty("value", 0.0007)
        self.doubleSpinBox_tgap.setObjectName("doubleSpinBox_tgap")
        self.gridLayout_8.addWidget(self.doubleSpinBox_tgap, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(picking_parameters)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_31 = QtGui.QLabel(picking_parameters)
        self.label_31.setMinimumSize(QtCore.QSize(0, 20))
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_refreshPlot = QtGui.QPushButton(picking_parameters)
        self.pushButton_refreshPlot.setObjectName("pushButton_refreshPlot")
        self.gridLayout_9.addWidget(self.pushButton_refreshPlot, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 2, 1, 1)
        self.comboBox_shots = QtGui.QComboBox(picking_parameters)
        self.comboBox_shots.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_shots.setObjectName("comboBox_shots")
        self.gridLayout_9.addWidget(self.comboBox_shots, 0, 1, 1, 1)
        self.label_32 = QtGui.QLabel(picking_parameters)
        self.label_32.setObjectName("label_32")
        self.gridLayout_9.addWidget(self.label_32, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(picking_parameters)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 0, 0, 1, 1)
        self.comboBox_traces = QtGui.QComboBox(picking_parameters)
        self.comboBox_traces.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_traces.setObjectName("comboBox_traces")
        self.gridLayout_9.addWidget(self.comboBox_traces, 0, 4, 1, 1)
        self.checkBox_auto_refresh = QtGui.QCheckBox(picking_parameters)
        self.checkBox_auto_refresh.setChecked(True)
        self.checkBox_auto_refresh.setObjectName("checkBox_auto_refresh")
        self.gridLayout_9.addWidget(self.checkBox_auto_refresh, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_trace_plot = QtGui.QVBoxLayout()
        self.verticalLayout_trace_plot.setObjectName("verticalLayout_trace_plot")
        self.verticalLayout_2.addLayout(self.verticalLayout_trace_plot)
        self.verticalLayout_2.setStretch(9, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_4 = QtGui.QFrame(picking_parameters)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_snr = QtGui.QVBoxLayout()
        self.verticalLayout_snr.setObjectName("verticalLayout_snr")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtGui.QLabel(picking_parameters)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.radioButton_const = QtGui.QRadioButton(picking_parameters)
        self.radioButton_const.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_const.setChecked(False)
        self.radioButton_const.setObjectName("radioButton_const")
        self.horizontalLayout_9.addWidget(self.radioButton_const)
        self.radioButton_dyn = QtGui.QRadioButton(picking_parameters)
        self.radioButton_dyn.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_dyn.setChecked(True)
        self.radioButton_dyn.setObjectName("radioButton_dyn")
        self.horizontalLayout_9.addWidget(self.radioButton_dyn)
        self.horizontalLayout_9.setStretch(0, 1)
        self.verticalLayout_snr.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtGui.QLabel(picking_parameters)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.doubleSpinBox_constSNR = QtGui.QDoubleSpinBox(picking_parameters)
        self.doubleSpinBox_constSNR.setMinimumSize(QtCore.QSize(0, 20))
        self.doubleSpinBox_constSNR.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_constSNR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_constSNR.setDecimals(1)
        self.doubleSpinBox_constSNR.setMinimum(1.0)
        self.doubleSpinBox_constSNR.setMaximum(10000.0)
        self.doubleSpinBox_constSNR.setSingleStep(0.1)
        self.doubleSpinBox_constSNR.setProperty("value", 8.0)
        self.doubleSpinBox_constSNR.setObjectName("doubleSpinBox_constSNR")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_constSNR)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_snr.addLayout(self.horizontalLayout_10)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(picking_parameters)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(picking_parameters)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.p1 = QtGui.QDoubleSpinBox(picking_parameters)
        self.p1.setMinimumSize(QtCore.QSize(0, 20))
        self.p1.setDecimals(4)
        self.p1.setMinimum(-100.0)
        self.p1.setMaximum(100.0)
        self.p1.setSingleStep(0.0001)
        self.p1.setProperty("value", 0.004)
        self.p1.setObjectName("p1")
        self.gridLayout_2.addWidget(self.p1, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(picking_parameters)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(picking_parameters)
        self.label_12.setMinimumSize(QtCore.QSize(0, 20))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 3, 1, 1)
        self.p2 = QtGui.QDoubleSpinBox(picking_parameters)
        self.p2.setMinimumSize(QtCore.QSize(0, 20))
        self.p2.setDecimals(4)
        self.p2.setMinimum(-100.0)
        self.p2.setMaximum(100.0)
        self.p2.setSingleStep(0.0001)
        self.p2.setProperty("value", -0.0007)
        self.p2.setObjectName("p2")
        self.gridLayout_2.addWidget(self.p2, 1, 4, 1, 1)
        self.shift_dist = QtGui.QSpinBox(picking_parameters)
        self.shift_dist.setMinimumSize(QtCore.QSize(0, 20))
        self.shift_dist.setMinimum(-10000)
        self.shift_dist.setMaximum(10000)
        self.shift_dist.setProperty("value", 30)
        self.shift_dist.setObjectName("shift_dist")
        self.gridLayout_2.addWidget(self.shift_dist, 0, 1, 1, 1)
        self.shift_snr = QtGui.QSpinBox(picking_parameters)
        self.shift_snr.setMinimumSize(QtCore.QSize(0, 20))
        self.shift_snr.setMinimum(-10000)
        self.shift_snr.setMaximum(10000)
        self.shift_snr.setProperty("value", 100)
        self.shift_snr.setObjectName("shift_snr")
        self.gridLayout_2.addWidget(self.shift_snr, 0, 4, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.verticalLayout_snr.addLayout(self.gridLayout_2)
        self.verticalLayout_snr.setStretch(0, 1)
        self.verticalLayout_snr.setStretch(1, 1)
        self.verticalLayout_snr.setStretch(2, 2)
        self.verticalLayout_5.addLayout(self.verticalLayout_snr)
        self.vlayout_plot = QtGui.QVBoxLayout()
        self.vlayout_plot.setObjectName("vlayout_plot")
        self.verticalLayout_5.addLayout(self.vlayout_plot)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.label_eta = QtGui.QLabel(picking_parameters)
        self.label_eta.setText("")
        self.label_eta.setObjectName("label_eta")
        self.horizontalLayout_14.addWidget(self.label_eta)
        self.buttonBox = QtGui.QDialogButtonBox(picking_parameters)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_14.addWidget(self.buttonBox)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)

        self.retranslateUi(picking_parameters)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), picking_parameters.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), picking_parameters.reject)
        QtCore.QMetaObject.connectSlotsByName(picking_parameters)

    def retranslateUi(self, picking_parameters):
        picking_parameters.setWindowTitle(QtGui.QApplication.translate("picking_parameters", "Picking Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("picking_parameters", "Choose parameters for picking (picker tuning)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Minimum permitted direct velocity (<span style=\" font-weight:600;\">apparent</span><span style=\" font-weight:600;\">velocity</span> calculated on direct distance between source and receiver!).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("picking_parameters", "vmin [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmax.setText(QtGui.QApplication.translate("picking_parameters", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("picking_parameters", "[m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Maximum permitted direct velocity (<span style=\" font-weight:600;\">apparent</span><span style=\" font-weight:600;\">velocity</span> calculated on direct distance between source and receiver!).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("picking_parameters", "vmax [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("picking_parameters", "[m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Amount of CPU kernels used/processes spawned for picking algorithm.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("picking_parameters", "Number of CPU cores used [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmin.setText(QtGui.QApplication.translate("picking_parameters", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("picking_parameters", "Characteristic Function Calculation Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("picking_parameters", "[s] to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("picking_parameters", "from", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Take only a part of the trace from [...] to [...] seconds.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("picking_parameters", "Cut seismograms [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Length of the moving window used for calculation of the characteristic function.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("picking_parameters", "Length of the moving window [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("picking_parameters", "[s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("picking_parameters", "[s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("picking_parameters", "Value between 1 and 100 % for threshold picking algorithm (Default = 60%).", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("picking_parameters", "Fraction of local maximum for HOS [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_folm.setText(QtGui.QApplication.translate("picking_parameters", "60 %", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_aicright.setText(QtGui.QApplication.translate("picking_parameters", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_aicleft.setText(QtGui.QApplication.translate("picking_parameters", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setToolTip(QtGui.QApplication.translate("picking_parameters", "Samples before and after initial HOS pick.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("picking_parameters", "[samples]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("picking_parameters", "Samples before and after initial HOS pick.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("picking_parameters", "AIC window (only if AIC is checked) [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("picking_parameters", "Use additional Akaike Information Criterion for picking.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("picking_parameters", "AIC [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Generate a QThread object for the autopicker, preventing the GUI from freezing.</p><p>Recommended to activate this, but can be deactivated in case multiprocessing does not work properly.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("picking_parameters", "Threading [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("picking_parameters", "SNR Calculation Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Estimated, average length of the awaited signal for SNR calculation.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("picking_parameters", "Signal window [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("picking_parameters", "[s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("picking_parameters", "[s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setToolTip(QtGui.QApplication.translate("picking_parameters", "<html><head/><body><p>Length of the safety gap between signal and noise window for SNR calculation.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("picking_parameters", "Gap length [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("picking_parameters", "Plot example shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_refreshPlot.setText(QtGui.QApplication.translate("picking_parameters", "Refresh Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("picking_parameters", "TraceID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("picking_parameters", "Shotnumber:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_auto_refresh.setText(QtGui.QApplication.translate("picking_parameters", "auto refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("picking_parameters", "SNR threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_const.setText(QtGui.QApplication.translate("picking_parameters", "constant", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_dyn.setText(QtGui.QApplication.translate("picking_parameters", "distance dependent (advanced)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("picking_parameters", "Constant SNR threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("picking_parameters", "Shift distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("picking_parameters", "p1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("picking_parameters", "Shift SNR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("picking_parameters", "p2", None, QtGui.QApplication.UnicodeUTF8))

